version: '3.4'

services:
  database:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: qwerty
  redis:
    image: redis:5.0.7
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    environment:
      RAILS_ENV: development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: qwerty
      DATABASE_HOST: database
      REDIS_HOST: redis
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - app      
      - database
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    environment:
      RAILS_ENV: development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: qwerty
      DATABASE_HOST: database
      REDIS_HOST: redis
    entrypoint: ./bin/sidekiq-entrypoint.sh
volumes:
  gem_cache:
  node_modules:
